(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(c-basic-offset 3)
 '(c-block-comment-prefix "")
 '(c-comment-only-line-offset 0)
 '(c-offsets-alist (quote ((c . 0) (defun-block-intro . +) (inline-open . +) (brace-list-open . 0) (brace-list-intro . +) (statement-case-open . 0) (substatement-open . 0) (case-label . +) (comment-intro . 0))))
 '(c-tab-always-indent (quote other))
 '(column-number-mode t)
 '(compilation-search-path (quote ("c:\\sys_en")))
 '(compile-command "delphi32.exe -b dsr4660.dpr")
 '(delphi-indent-level 2)
 '(desktop-save t)
 '(diff-command "diff")
 '(display-time-mode t)
 '(ecb-gzip-setup (quote cons))
 '(ecb-options-version "2.32")
 '(ecb-tar-setup (quote cons))
 '(ediff-cmp-program "cmp")
 '(ediff-diff-options "--binary -w")
 '(ediff-diff-program "diff")
 '(ediff-diff3-program "diff3")
 '(emms-player-paused-hook nil)
 '(emms-player-started-hook (quote (emms-show)))
 '(emms-playlist-mode-center-when-go t)
 '(face-font-family-alternatives (quote (("-outline-Lucida Console-normal-r-normal-normal-13-97-96-96-c-*-iso8859-1") ("courier" "fixed") ("helv" "helvetica" "arial" "fixed"))))
 '(hide-ifdef-initially t)
 '(icicle-reminder-prompt-flag 6)
 '(initial-scratch-message nil)
 '(ispell-program-name "c:/utils/aspell/bin/aspell.exe" t)
 '(kill-ring-max 600)
 '(lj-default-username "rooijan")
 '(locate-command "\"ack.pl\"")
 '(max-lisp-eval-depth 10000)
 '(max-specpdl-size 30000)
 '(org-emphasis-alist (quote (("$" bold "<b>" "</b>") ("*" bold "<b>" "</b>") ("&" italic "<i>" "</i>") ("/" italic "<i>" "</i>") ("_" underline "<u>" "</u>") ("=" org-code "<code>" "</code>") ("+" (:strike-through t) "<del>" "</del>"))))
 '(org-startup-folded nil)
 '(package-archives (quote (("marmalade" . "https://marmalade-repo.org/packages/") ("gnu" . "http://elpa.gnu.org/packages/"))))
 '(package-selected-packages (quote (elpy yasnippet expand-region)))
 '(pgg-gpg-program "gpg")
 '(ses-after-entry-functions (quote (next-line)))
 '(show-paren-mode t)
 '(speedbar-tag-hierarchy-method (quote (speedbar-sort-tag-hierarchy)))
 '(sql-mysql-options (quote ("\"-t -f -n\"")))
 '(sql-mysql-program "c:/xampp/mysql/bin/mysql.exe")
 '(svn-status-hide-unknown t)
 '(svn-status-hide-unmodified t)
 '(tramp-methods (quote (("smb") ("ftp") ("rcp" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "rsh") (tramp-copy-program "rcp") (tramp-remote-sh "/bin/sh") (tramp-login-args nil) (tramp-copy-args nil) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)) ("scp" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program "scp") (tramp-remote-sh "/bin/sh") (tramp-login-args ("-e" "none")) (tramp-copy-args nil) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)) ("scp1" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program "scp") (tramp-remote-sh "/bin/sh") (tramp-login-args ("-1" "-e" "none")) (tramp-copy-args ("-1")) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)) ("scp2" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program "scp") (tramp-remote-sh "/bin/sh") (tramp-login-args ("-2" "-e" "none")) (tramp-copy-args ("-2")) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)) ("scp1_old" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh1") (tramp-copy-program "scp1") (tramp-remote-sh "/bin/sh") (tramp-login-args ("-e" "none")) (tramp-copy-args nil) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)) ("scp2_old" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh2") (tramp-copy-program "scp2") (tramp-remote-sh "/bin/sh") (tramp-login-args ("-e" "none")) (tramp-copy-args nil) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)) ("rsync" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program "rsync") (tramp-remote-sh "/bin/sh") (tramp-login-args ("-e" "none")) (tramp-copy-args ("-e" "ssh")) (tramp-copy-keep-date-arg "-t") (tramp-password-end-of-line nil)) ("remcp" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "remsh") (tramp-copy-program "rcp") (tramp-remote-sh "/bin/sh") (tramp-login-args nil) (tramp-copy-args nil) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)) ("rsh" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "rsh") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args nil) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("ssh" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-e" "none")) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("ssh1" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-1" "-e" "none")) (tramp-copy-args ("-1")) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("ssh2" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-2" "-e" "none")) (tramp-copy-args ("-2")) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("ssh1_old" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh1") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-e" "none")) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("ssh2_old" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh2") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-e" "none")) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("remsh" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "remsh") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args nil) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("telnet" (tramp-connection-function tramp-open-connection-telnet) (tramp-login-program "telnet") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args nil) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("su" (tramp-connection-function tramp-open-connection-su) (tramp-login-program "su") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-" "%u")) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("sudo" (tramp-connection-function tramp-open-connection-su) (tramp-login-program "sudo") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-u" "%u" "-s" "-p" "Password:")) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("multi" (tramp-connection-function tramp-open-connection-multi) (tramp-login-program nil) (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args nil) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("scpc" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program "scp") (tramp-remote-sh "/bin/sh") (tramp-login-args ("-o" "ControlPath=%t.%%r@%%h:%%p" "-o" "ControlMaster=yes" "-e" "none")) (tramp-copy-args ("-o" "ControlPath=%t.%%r@%%h:%%p" "-o" "ControlMaster=auto")) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)) ("scpx" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program "scp") (tramp-remote-sh "/bin/sh") (tramp-login-args ("-e" "none" "-t" "-t" "/bin/sh")) (tramp-copy-args nil) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)) ("sshx" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "ssh") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-e" "none" "-t" "-t" "/bin/sh")) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("krlogin" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "krlogin") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-x")) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line nil)) ("plink" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "plink.exe") (tramp-copy-program nil) (tramp-remote-sh "/bin/bash") (tramp-login-args ("-ssh" "foo")) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line "xy")) ("plinkssh" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "plinkssh.exe") (tramp-copy-program nil) (tramp-remote-sh "/bin/bash") (tramp-login-args (nil)) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line "xy")) ("plink1" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "plink.exe") (tramp-copy-program nil) (tramp-remote-sh "/bin/sh") (tramp-login-args ("-1" "-ssh")) (tramp-copy-args nil) (tramp-copy-keep-date-arg nil) (tramp-password-end-of-line "xy")) ("pscp" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "plink.exe") (tramp-copy-program "pscp") (tramp-remote-sh "/bin/sh") (tramp-login-args ("-ssh")) (tramp-copy-args nil) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line "xy")) ("fcp" (tramp-connection-function tramp-open-connection-rsh) (tramp-login-program "fsh") (tramp-copy-program "fcp") (tramp-remote-sh "/bin/sh -i") (tramp-login-args ("sh" "-i")) (tramp-copy-args nil) (tramp-copy-keep-date-arg "-p") (tramp-password-end-of-line nil)))) t)
 '(tramp-multi-connection-function-alist (quote (("telnet" tramp-multi-connect-telnet "telnet %h%n") ("rsh" tramp-multi-connect-rlogin "rsh %h -l %u%n") ("remsh" tramp-multi-connect-rlogin "remsh %h -l %u%n") ("ssh" tramp-multi-connect-rlogin "ssh %h -l %u%n") ("ssht" tramp-multi-connect-rlogin "ssh %h -e none -t -t -l %u%n") ("su" tramp-multi-connect-su "su - %u%n") ("sudo" tramp-multi-connect-su "sudo -u %u -s -p Password:%n") ("plink" tramp-multi-connect-rlogin "plink.exe -ssh %h -l %u%n"))))
 '(transient-mark-mode t)
 '(twit-follow-idle-interval 300)
 '(twit-user "rooijan")
 '(twitter-password nil t)
 '(twitter-username "rooijan" t)
 '(w32shell-shell (quote cmd)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :background "Black" :foreground "LightGray" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 90 :width normal :family "adobe-courier"))))
 '(rst-level-1-face ((t (:background "blue"))) t)
 '(rst-level-2-face ((t (:background "blue"))) t)
 '(rst-level-3-face ((t (:background "blue"))) t)
 '(rst-level-4-face ((t (:background "blue"))) t)
 '(rst-level-5-face ((t (:background "blue"))) t)
 '(rst-level-6-face ((t (:background "blue"))) t)
 '(twitter-time-stamp-face ((t (:foreground "green" :slant italic))))
 '(twitter-user-name-face ((t (:foreground "red" :weight bold)))))
